spring:
  datasource:
    url: jdbc:postgresql://db:5432/vingo
    username: vingo
    password: vingo123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always